<script lang="ts">
	import { sendUserToast } from '$lib/utils'
	import { Button, Alert } from '$lib/components/common'
	import Label from '$lib/components/Label.svelte'
	import ClipboardPanel from '$lib/components/details/ClipboardPanel.svelte'
	import { Save, ExternalLink } from 'lucide-svelte'

	interface Props {
		serviceName: string
		serviceDisplayName: string
		existingConfig?: {
			client_id: string
			client_secret: string
			base_url: string
		} | null
		redirectUri: string
		onConfigSaved: (oauthData: any) => Promise<void>
		requiresBaseUrl?: boolean
		baseUrlLabel?: string
		baseUrlPlaceholder?: string
		baseUrlSettingsPath?: string
		clientIdPlaceholder?: string
		clientSecretPlaceholder?: string
		setupInstructions?: string[]
	}

	let {
		serviceName,
		serviceDisplayName,
		existingConfig,
		onConfigSaved,
		redirectUri,
		requiresBaseUrl = true,
		baseUrlLabel = `${serviceDisplayName} base URL`,
		baseUrlPlaceholder = `https://your-${serviceName}.example.com`,
		baseUrlSettingsPath = '/settings/admin/security',
		clientIdPlaceholder = `Generated by ${serviceDisplayName} OAuth app`,
		clientSecretPlaceholder = `Generated by ${serviceDisplayName} OAuth app`,
		setupInstructions
	}: Props = $props()

	let saving = $state(false)
	let clientId = $state('')
	let clientSecret = $state('')
	let baseUrl = $state('')
	$effect(() => {
		if (existingConfig) {
			clientId = existingConfig.client_id
			clientSecret = existingConfig.client_secret
			baseUrl = existingConfig.base_url
		}
	})

	let canSave = $derived(
		!saving &&
			!!clientId.trim() &&
			!!clientSecret.trim() &&
			(!requiresBaseUrl || !!baseUrl.trim())
	)

	async function saveConfig() {
		if (!canSave) {
			sendUserToast('请填写所有必填字段', true)
			return
		}

		saving = true
		try {
			const oauthData: Record<string, string> = {
				client_id: clientId.trim(),
				client_secret: clientSecret.trim(),
				base_url: requiresBaseUrl ? baseUrl.trim().replace(/\/+$/, '') : '',
				redirect_uri: redirectUri.trim()
			}

			await onConfigSaved(oauthData)
			resetForm()
		} catch (err: any) {
			sendUserToast(`配置 OAuth 客户端失败：${err.message}`, true)
		} finally {
			saving = false
		}
	}

	function resetForm() {
		clientId = ''
		clientSecret = ''
	}


</script>

<div class="space-y-4">
	<div class="flex justify-between items-center">
			<h4 class="text-md font-medium text-primary">{serviceDisplayName} OAuth 客户端配置</h4
		>
	</div>

	{#if !existingConfig}
			<Alert type="warning" title="需要 OAuth 客户端">
				<p class="text-sm mb-2">
					连接 {serviceDisplayName} 前，需要先配置 OAuth 客户端。
				</p>
			{#if setupInstructions}
				<ol class="list-decimal list-inside space-y-1 text-sm">
					{#each setupInstructions as instruction}
						<li>{@html instruction}</li>
					{/each}
				</ol>
			{/if}
		</Alert>
	{/if}

	<div class="space-y-4">
		<div class="space-y-4">
			{#if requiresBaseUrl}
				<div class="flex flex-col gap-1">
					<Label label={baseUrlLabel} />
					<p class="text-xs font-normal text-secondary"
						>{serviceDisplayName} 实例的基础 URL（末尾不带斜杠）</p
					>
					<input
						type="url"
						bind:value={baseUrl}
						placeholder={baseUrlPlaceholder}
						class="windmill-input"
						disabled={saving}
					/>
					{#if baseUrl && baseUrlSettingsPath}
						<Button
							wrapperClasses="self-start"
							href={`${baseUrl}${baseUrlSettingsPath}`}
							target="_blank"
							startIcon={{ icon: ExternalLink }}
						>
								{serviceDisplayName} OAuth 设置
						</Button>
					{/if}
				</div>
			{/if}

			<div class="flex flex-col gap-1">
				<Label label="重定向 URI" />
				<p class="text-xs font-normal text-secondary"
					>在 {serviceDisplayName} 中创建 OAuth 应用时使用此 URL</p
				>
				<ClipboardPanel content={redirectUri} size="sm" />
			</div>

			<div class="flex flex-col gap-1">
				<Label label="客户端 ID" />
				<input
					type="text"
					bind:value={clientId}
					placeholder={clientIdPlaceholder}
					class="windmill-input"
					disabled={saving}
				/>
			</div>

			<div class="flex flex-col gap-1">
				<Label label="客户端密钥" />
				<input
					type="password"
					bind:value={clientSecret}
					placeholder={clientSecretPlaceholder}
					class="windmill-input"
					disabled={saving}
				/>
			</div>

			<div class="flex gap-2">
				<Button
					color="blue"
					onclick={saveConfig}
					disabled={!canSave}
					startIcon={{ icon: Save }}
				>
					{saving ? '保存中...' : '保存配置'}
				</Button>
			</div>
		</div>
	</div>

	{#if existingConfig}
			<Alert type="success" title="OAuth 客户端已配置">
				<p class="text-sm">
					已为 {serviceDisplayName} 配置 OAuth 客户端。现在可以将此工作区连接到 {serviceDisplayName}。
				</p>
			</Alert>
	{/if}
</div>
